### ISSUE TITLE
TBI Sheet in the Main excel file

### ISSUE THREAD

**Issue by Anderbug** [JamesDMSpeed/AfricanBioServices-Vegetation-and-soils#2]
Stu, could you have a look at the TBI sheet in the main excel file and see if I should remove some of the variables? What do the TBI people want? I was wondering if I should remove the teabags which has cheating. Or maybe just remove all the open treatments? I did K and S as done by Keushamp, and also K and S done by Mueller (the one you met at the TBI conference/heard about?). I have not done any statistics to see whether this has any significance for my results or not. Should I remove the column for Mueller? And keep it for myself and my own data analysis later?

**Comment by anotherswsmith** [comment]
Anders, I have uploaded an example submission for the Tea4Science datasheet (AfricanBioServices-Vegetation-and-soils/Termites/Teatime4science.Serengeti.EXAMPLE.xlsx). I think in your excel you follow this. Though you also need to include the above section with location details etc. You can include average soil moisture and temperature, and you also know the soil texture type for each block (see where your sites fit in texture triangle). Just fill in the excel sheet and see if it calculates K and S, for the instances that it does not work then this likely relates to no litter mass due to termites. I would not use Mueller in the sheet, I believe the teabag people are aware of this issue. We can leave looking at S and K rates until later, once you are happy that you have the complete dataset.

I am struggle to open your csv files. They seem to be seperated by ";", although when attempting to format them, I still get too may semi-commas. Could you try saving them as comma formatted files rather than semi comma?

**Comment by Anderbug** [comment]
Ok, nice. Yes I have just used raw unashed data for the K and S since I dont have this for the dry season. I included the raw data of dry season as well in the TBI sheet (further down the sheet). I could make two columns for K(unashed, K(ashed) and S(unashed) and S(ashed)?

But, it seems like I should make two separate TBI sheets, one for wet and one for dry? Now I have it in one sheet. The separted sheets I have now for wet and dry is only for my own R analysis and not for delivering to Judith.

Yes, I was struggling with the csv myself. I was meant to create "," separated, but I gave up yesterday. I'll try again. 

I'll let you know when I'm done and satisfied with the TBI sheet(s). When is the deadline, if there are any?

**Comment by JamesDMSpeed** [comment]
I have added a short script to read in csv from a Norwegian locale (sep=';') into R. I also wrote out the TBI sheet as a comma seperated.

Anders, if you want to send a part of the data to someone, you can subset/index it within R and write a csv with just the data you want.
