### ISSUE TITLE
Singularity fit when modelling

### ISSUE THREAD

**Issue by Anderbug** [JamesDMSpeed/AfricanBioServices-Vegetation-and-soils#3]
I will start using this issue function on GitHub from now on relating to script problems. Here goes:

I have some problem with singularity fit and I'm not understanding it. I assume it is a problem of the random factor. Previously it was written (Site.ID|blockdesign.num). Now I've wirtten (1|blockdesign.num). Now singularity fit is no problem anymore. BUT am I correclty using the random factor in releation to my experimental design? I have problems understanding this. See link under for location in the script.

https://github.com/JamesDMSpeed/AfricanBioServices-Vegetation-and-soils/blob/d0ecd499cfcc86dfddbabc2ee7cc4ac0e7e4aca6/Termites/Anders_MSc_script.R#L981-L991

**Comment by anotherswsmith** [comment]
Anders,
Your model runs with site and block number as random factors. It should be written as (1|Site.ID/blockdesign.num) and NOT (Site.ID|blockdesign.num). The former just has random structure block is nested design, while the latter is more complicated random structure. There is no singularity issues I even checked with region:landuse factor that should be a problem and it did not seem to inflate Sum of Sqs compared to block only. It seems most of the variation is found in the block rather than site, nevertheless I would still include site. Double check the factors you wish to include in the model you have many, so it is good to start getting into using dredge. 

Random effects:
 Groups                  Name                  Variance Std.Dev.
 blockdesign.num:Site.ID (Intercept) 82.13    9.062   
 Site.ID                                (Intercept)  0.00    0.000   
 Residual                                                 77.98    8.831   

Stu

**Comment by Anderbug** [comment]
Stu, I still get signular fit message....

My model now looks  like this (I have not included interactions yet due to
the issue):
LabileMainMod <- lmer(Massloss.per~Season+Landuse+Region+
                        Treatment+Sand+Temp+C.N+
                        (1|Site.ID/blockdesign.num), na.action=na.omit,REML
= F,data=LabileMain)

When I remove Region from model, I get no singularity fit. I'm not
understanding this. Why does it work for you, and not me?

And what do you mean by double checking? For collinearity?

-Anders




ons. 20. mar. 2019 kl. 13:45 skrev Stuart Smith <notifications@github.com>:

**Comment by anotherswsmith** [comment]
Anders,
Can you provide the error message you are getting? Perhaps this has more detail. I am just running your script down to the 990 lines and I can produce the model you outlined above without issue. Have you changes something for site.ID or blockdeisgn.num so that they are not factors? There should be no reason that region would be singular with random structure, this would only be the case for region:landuse interaction (i,e, site.ID:block = the same thing), but as I said earlier I do not get this issue either. 
Stu

**Comment by Anderbug** [comment]
The only error mesages is: "singular fit" when i run the model:

This is the output:

*First running the model:*
> LabileMainMod <- lmer(Massloss.per~Season+Landuse+Region+
+                         Treatment+Sand+Temp+C.N+
+
#Season:Landuse+Season:Treatment+Season:Sand+Season:Temp+
+
 #Season:C.N+Landuse:Treatment+Landuse:Sand+Landuse:Temp+Landuse:C.N+
+                         #Treatment:Sand+Treatment:Temp+Treatment:C.N+
+                         #Sand:Temp+Sand:C.N+
+                         #Temp:C.N+
+                         (1|Site.ID/blockdesign.num),
na.action=na.omit,REML = F,data=LabileMain)
singular fit

*Then summary:*
> summary(LabileMainMod)
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: Massloss.per ~ Season + Landuse + Region + Treatment + Sand +
    Temp + C.N + (1 | Site.ID/blockdesign.num)
   Data: LabileMain

     AIC      BIC   logLik deviance df.resid
  5447.4   5507.0  -2710.7   5421.4      712

Scaled residuals:
    Min      1Q  Median      3Q     Max
-5.0004 -0.3982 -0.0247  0.2549  4.4272

Random effects:
 Groups                  Name        Variance Std.Dev.
 blockdesign.num:Site.ID (Intercept) 194.57   13.949
 Site.ID                 (Intercept)   0.00    0.000
 Residual                             79.54    8.918
Number of obs: 725, groups:  blockdesign.num:Site.ID, 56; Site.ID, 7

Fixed effects:
                   Estimate Std. Error t value
(Intercept)          2.6855    18.4772   0.145
SeasonWet           29.5032     3.8804   7.603
LandusePasture      -9.3678     5.1423  -1.822
LanduseWild         -6.2252     5.3370  -1.166
RegionWet           24.2136     4.4661   5.422
RegionIntermediate  13.0647     7.1926   1.816
TreatmentOpen        0.7953     0.6626   1.200
Sand                 0.1865     0.1084   1.720
Temp                 0.3632     0.2940   1.236
C.N                  1.0228     1.3600   0.752

Correlation of Fixed Effects:
            (Intr) SesnWt LndsPs LndsWl RegnWt RgnInt TrtmnO Sand   Temp
SeasonWet   -0.271
LandusePstr  0.016 -0.017
LanduseWild  0.172 -0.061  0.475
RegionWet    0.191 -0.069  0.063  0.070
RegnIntrmdt  0.004  0.004  0.072 -0.379  0.339
TreatmntOpn -0.019  0.001  0.000  0.000 -0.001 -0.001
Sand        -0.121 -0.030 -0.192  0.122 -0.146 -0.385  0.000
Temp        -0.335  0.152 -0.017 -0.114 -0.312 -0.044  0.001 -0.129
C.N         -0.862  0.129 -0.106 -0.314 -0.145  0.082  0.000 -0.072 -0.048
convergence code: 0
singular fit

tor. 21. mar. 2019 kl. 11:16 skrev Stuart Smith <notifications@github.com>:

**Comment by Anderbug** [comment]
..But when I run the full model (including all the hashed variables above)
I get no singular fit...

Strange?
-Anders

tor. 21. mar. 2019 kl. 11:26 skrev Anders Sundsdal <an.sundsdal@gmail.com>:

**Comment by anotherswsmith** [comment]
OK. You have 6 more blocks in your design than the model I run, can you try uploading your new code please. The random structure I have for the same model is below. 7 sites, but 6 less blocks...but even these numbers suggest some issues. Your current block structure = landuse.

Also how is there 7 sites? Surely there is 5 - Makao, Maswa, Seronera, Handjega and Mwantimba. Within each of them there is 4 blocks, so 20 combinations in total. Therefore how are we getting 56 and 50? Your site should not be landuse as this will create problems, the random structure is meant to reflect the geographical similarity of the design, that you have not controlled for.

If you look at ...
table(LabileMain$Site.ID,LabileMain$blockdesign.num)
There seems to be 16 blocks within each site? Are these plots? Your structure can be site (5 outline above), block (4 blocks per land-use but then 8 in a village and 4 in wildlife protected area - I think this makes sense as agri sites were much closer to pastures compared to wildlife sites), plot (2 litterbages in same plot i.e. green exclose and open). 

I would therefore suggest a structure of (1|Site/block/ plot) - try it and see if it works. 

Random effects:
 Groups                  Name        Variance Std.Dev.
 blockdesign.num:Site.ID (Intercept) 45.05    6.712   
 Site.ID                 (Intercept) 10.51    3.241   
 Residual                            80.15    8.952   
Number of obs: 725, groups:  blockdesign.num:Site.ID, 50; Site.ID, 7

**Comment by anotherswsmith** [comment]
Sorry just to correct, there would not be 20 blocks in total, but 28. 8 blocks in Makoa and Mwantimba, 4 in Maswa and Hand, 4 in Seronera. So what should be the random effect structure

Number of obs: 725, groups: plot...blockdesign.num:Site.ID, 28; Site.ID, 5

**Comment by Anderbug** [comment]
Hmm...
It is 7 sites due to Site.ID:
*Site.ID* has the levels:  "Handajega"    "Makao.ag"     "Makao.p"
"Maswa"        "Mwantimba.ag" "Mwantimba.p"  "Seronera" . 7 in total.
And *Site *has: "Handajega" "Makao"     "Maswa"     "Mwantimba" "Seronera".

And block is 56 due to season as well.  It's 28 within a Season, but for
both season its 56. I made my *blockdesign.num* by:
Season,Region,Landuse,Blockcode.
But, Now I've done *blockdesign.num* by: Site,Block,Landuse. In summary it
the gives 28. (Scriptline 972)

I think I made the Site.ID factor as I thought that would reflect my design
better in the random term... But maybe it's not correct as it now is
Site:Landuse?

I tried using randomfactor: (1|Site/blockdesign.num)
or (1|Site/blockdesign.num/Plot) --> *Still Singular fit....*


*Output from summary with (1|Site/blockdesign.num/Plot):*
*Random effects:*
* Groups                      Name        Variance Std.Dev.*
* Plot:(blockdesign.num:Site) (Intercept)   0.00    0.000  *
* blockdesign.num:Site        (Intercept)  20.64    4.543  *
* Site                        (Intercept)   0.00    0.000  *
* Residual                                208.72   14.447  *
*Number of obs: 725, groups:  *
*Plot:(blockdesign.num:Site), 190; blockdesign.num:Site, 28; Site, 5*

I'm not sure if "Plot:(blockdesign.num:Site), 190" is correct. It should
have 192....Is there a problem that the CG part of the data has plot
numbering from 193-220? And or is it because some rows are na. so losing
two plots?

I'm on my cellular phone data so I'll upload the updated script here.
Hopefully GitHub will work later today when we're at the library.

PS! Previously Seronera was merged into one block, but I made it back into
4 blocks after our meeting.
PSS! Model gets no singular fit if I add all the interactions previously
hashed...as I wrote previously.

-Anders

tor. 21. mar. 2019 kl. 11:44 skrev Stuart Smith <notifications@github.com>:

**Comment by anotherswsmith** [comment]
Anders,

We are not working on the same script, so it is a bit hard for me to help here. I will wait until you upload what you have done. On the old script 

I can changed Site ID = site and reran the model with Site/Blockcode/Plot as random factors - I get no singularity issues with region. However, I can see that Seronera has only 1 block, so I am not sure if this is an issue when it contains 4 blocks. I will have to wait for you to upload your revised script. 

levels(LabileMain$Site.ID)<-c("Handajega","Makao","Makao","Maswa", "Mwantimba", "Mwantimba", "Seronera")
LabileMain$Blockcode<-as.factor(LabileMain$Blockcode)
levels(LabileMain$Blockcode)
LabileMain$Plot<-as.factor(LabileMain$Plot)
SUMMARY
LabileMainMod <- lmer(Massloss.per~Season+Landuse+Treatment+Sand+Rain+Temp+C.N+
                        Region+
                        (1|Site.ID/Blockcode/Plot),na.action=na.omit,REML = T,data=LabileMain)
 Groups                   Name        Variance Std.Dev.
 Plot:(Blockcode:Site.ID) (Intercept)  7.516   2.742   
 Blockcode:Site.ID        (Intercept) 17.030   4.127   
 Site.ID                  (Intercept)  0.000   0.000   
 Residual                             96.453   9.821   
Number of obs: 725, groups:  
Plot:(Blockcode:Site.ID), 190; Blockcode:Site.ID, 25; Site.ID, 5 # Seronera is one block here - not four  - so 25 blocks rather than 28

I will not upload the script I have been editing so as not to cause issues with push and pull.

**Comment by Anderbug** [comment]
Ah ok, that is not optimal. Better get GitHub working...

I tried using your scipt as above with block=25. One dissimilarity is the
Site:ID/Site term. I use Site (5 levels), while you use Site.ID which has 5
levels as well now. But that should be the same....
I also tried REML= F/REML=T.
Anyway, still singularity fit. I'll update you when things been updated on
Git.
And again, if I remove Region, no issue.

But still odd that you don't get this problem.

I'll just try out dredge function etc in the meantime.




tor. 21. mar. 2019 kl. 13:33 skrev Stuart Smith <notifications@github.com>:

**Comment by Anderbug** [comment]
Script now uploaded and updated. I tried again now (without seronera) and it worked when I set REML=T. When thats set to TRUE, then we test the random effects, right? When it is set REML=F then we test the fixed effects. I want to have REML=F when i do model selection, right? I still get singular fit when REML=F. So problem not solved...?

Output when REML=T and no singular fit:

Random effects:
 Groups                Name        Variance Std.Dev.
 Plot:(Blockcode:Site) (Intercept)  17.86    4.226  
 Blockcode:Site        (Intercept)  53.02    7.282  
 Site                  (Intercept)   3.17    1.780  
 Residual                          139.57   11.814  
Number of obs: 693, groups:  Plot:(Blockcode:Site), 186; Blockcode:Site, 24; Site, 4
